"""empty message

Revision ID: 5e642848dfc8
Revises: 
Create Date: 2023-10-20 11:03:26.688793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e642848dfc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
